[general]
# Opcional: CSV de fallback si no hay acceso a Sheets
GH_CSV_RAW_URL = "https://raw.githubusercontent.com/apoyomedicoips/estacionamientoips/main/data/formularios.csv"

[gcp_service_account]
type = "service_account"
project_id = "keen-genius-472215-q2"
private_key_id = "91efcea24a89e096bd291a3b24192181491827f2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCe9syJ3LqBYkTf
3ajFW2cZlbMdFxtgHDSvl7IqNRcN36o8DkO+17X2fi/Ug0IbtT/fPiRE5rDAhCXt
rd1j+sayGeAv6MIhegoYCuNV7mBIgfRiYugu65FBobsbe/+8/0kKtu9EuzcIKciS
/0+S/8749znbTAuznni1AXg5G/2hGFOXyHvdHop8kW5uB771Xcc9frG1MoUrQT86
OydI7KdY8S+EgmxkxfUyd0Z/HCZpto4Z7FZffT1siDqQpwKPrxk4g94VTLDIZSUs
qZNFzs114AZ1uFjCsu7q8Tp4Z2phzc1xxURJaJ2XKWZmQ5UiQPYWGJLyvObKCpLj
fXDbaeBxAgMBAAECggEAAQF+vWULPLwc3RZd88SJtVG3/U2VJL65ekkoOSk/Ix1R
zq+kFlSRMLQLAFXBavr3EWG8mHKMPO6LQzpcOYtHIJ00RH80hYaKC0+8DxVSEYti
KdWKrlQffXz5TzJT+wxIz53DAvxOedIQZWMvabJr6NPhHBcR8WsQZkwjGY6b7xV9
gnHzPZqBk8PZwB5pJHWOA4FEmGsmcAjFbdmbCHRDWLGtQt6WPxREJGhWAejQbmhR
0YI2a8lJz9/xe3cZlFGd6E8gASpRTn1gy607QUTDup6uK/RNVyhjHX12u+dn48Yw
nqUVNhx2RXwfVvaXhHYDPbP+RqRKMG+cJY1BlT0HcQKBgQDbfMaMuqRKXCfJy2x4
1/fcOGmNd4XGOBkSs88L1VX+d6eh2ohhrB7c0HzzSnGZ4FVwHazIuRTRRQ+70Bho
8icWlm/nesToTHpIb4hcSJYtmijIhM5w32uHK0wG2SclRvDJP7fsFoAVtCF6ocF/
i/JM1H+SGhvdSjkTUkx1StIHmQKBgQC5aIoORvGSxnBiEvnP9utKSi80DZjfwr3p
UzFQ8rtW6eUmembT5EfOXqhdMvxskNFX9OH/d6YlqASTPhfwzYgeFrQ8jdc4mTWU
XPkMNSE1ThJtlqeGSnCRTJthojsZNtdhvfMieTgTSKixDqlw+NjHdHc8zy8w6SWp
nGeQl/vGmQKBgAuEdarG1H4ubcwSB6QjuRbuQuOwhO2M3gv0MYYucK/EuaAtpoBx
lsEBk7z0iBeKBRG4DOwPgj8k/5lcZxuCsXhm9oJQF+sUsEoCyEYHbRIBh+hVx7t2
jd7u77NgS8SR/2qgFFeoKpp49FTKDixSPKm5cORKyHGJRot0Ax0YiwLpAoGAdFtH
8MfTCWLh2prADiSO6zN9RjSWUS8dEhX0qDF9IoFtHuXILIhiDABZtwutYNDNoF59
il7jdVRpcqKQUb4bA48KE8qMW+fCuVZTsbaSHareY8odXmjPFlC2XuJ6JkvFhYC4
2lSqvWdm/p8N9WkmWp4bypzXp+FZkoUmdZb8GlkCgYAB8QQcGJhJR1Zjrqs7x4UZ
46QM5oLD0sfbfqHvcOnjmTkvsvPAtMhBKXpWKz9ouNzCFmIdiWemafEpb2NZ1ytF
WNtjmoP1UUYdvZRGcPEJaYFlWgEBeuK24JyeuxA+/yLMeD36mK9saCP2vWvs2OKL
OK0v5roBM+7k+G00Xyk3NA==
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets-writer@keen-genius-472215-q2.iam.gserviceaccount.com"
client_id = "111948456452341318901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-writer%40keen-genius-472215-q2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

