[general]
# URL raw del CSV de fallback (opcional)
GH_CSV_RAW_URL = "https://raw.githubusercontent.com/apoyomedicoips/estacionamientoips/main/data/formularios.csv"

[gcp_service_account]
type = "service_account"
project_id = "TU_PROJECT_ID"
private_key_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIB...==\n-----END PRIVATE KEY-----\n"
client_email = "tu-servicio@tu-proyecto.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tu-servicio%40tu-proyecto.iam.gserviceaccount.com"
